modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/HttpRafa/BetterFarmland/issues"
license = "MIT"

[[mods]]
modId = "betterfarmland"
version = "${version}"
displayName = "BetterFarmland"
authors = "HttpRafa"
description = '''
Meant to improve your experience with your farmland
'''
#logoFile = "icon.png"

[[dependencies.betterfarmland]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterfarmland]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"